version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: nba_postgres
    restart: always
    environment:
      POSTGRES_USER: nba
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nba_stats
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: nba_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
